#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
第二阶段：变量命名统一脚本
处理驼峰与蛇形混用问题，统一函数调用命名
"""

import os
import re
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Set

class Stage2NamingUnifier:
    def __init__(self):
        self.src_dir = Path("src")
        self.backup_dir = Path("backups/stage2_naming_fixes")
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.report_file = f"stage2_naming_fixes_executed_{self.timestamp}.json"
        
        # 统计信息
        self.stats = {
            "files_processed": 0,
            "files_modified": 0,
            "total_replacements": 0,
            "replacement_types": {
                "variable_declarations": 0,
                "function_calls": 0,
                "object_properties": 0,
                "react_hooks": 0,
                "method_calls": 0
            }
        }
        
        # 详细修改记录
        self.modifications = []
        
        # 驼峰到蛇形的映射表
        self.camel_to_snake_mappings = {
            # React Hooks
            "useState": "use_state",
            "useEffect": "use_effect",
            "useContext": "use_context",
            "useReducer": "use_reducer",
            "useCallback": "use_callback",
            "useMemo": "use_memo",
            "useRef": "use_ref",
            "useImperativeHandle": "use_imperative_handle",
            "useLayoutEffect": "use_layout_effect",
            "useDebugValue": "use_debug_value",
            "useAuth": "use_auth",
            "usePermission": "use_permission",
            
            # 常用函数调用
            "setLoading": "set_loading",
            "setData": "set_data",
            "setError": "set_error",
            "setUser": "set_user",
            "setToken": "set_token",
            "setVisible": "set_visible",
            "setOpen": "set_open",
            "setSelected": "set_selected",
            "setActive": "set_active",
            "setDisabled": "set_disabled",
            "setFormData": "set_form_data",
            "setState": "set_state",
            "setConfig": "set_config",
            "setOptions": "set_options",
            "setItems": "set_items",
            "setList": "set_list",
            "setPage": "set_page",
            "setLimit": "set_limit",
            "setTotal": "set_total",
            "setCount": "set_count",
            "setIndex": "set_index",
            "setValue": "set_value",
            "setName": "set_name",
            "setTitle": "set_title",
            "setDescription": "set_description",
            "setContent": "set_content",
            "setMessage": "set_message",
            "setStatus": "set_status",
            "setType": "set_type",
            "setMode": "set_mode",
            "setSize": "set_size",
            "setColor": "set_color",
            "setStyle": "set_style",
            "setClass": "set_class",
            "setId": "set_id",
            "setKey": "set_key",
            "setUrl": "set_url",
            "setPath": "set_path",
            "setQuery": "set_query",
            "setParams": "set_params",
            "setHeaders": "set_headers",
            "setBody": "set_body",
            "setResponse": "set_response",
            "setResult": "set_result",
            "setOutput": "set_output",
            "setInput": "set_input",
            "setFilter": "set_filter",
            "setSort": "set_sort",
            "setOrder": "set_order",
            "setDirection": "set_direction",
            "setField": "set_field",
            "setColumn": "set_column",
            "setRow": "set_row",
            "setCell": "set_cell",
            "setTable": "set_table",
            "setGrid": "set_grid",
            "setLayout": "set_layout",
            "setPosition": "set_position",
            "setLocation": "set_location",
            "setCoordinates": "set_coordinates",
            "setDimensions": "set_dimensions",
            "setWidth": "set_width",
            "setHeight": "set_height",
            "setTop": "set_top",
            "setLeft": "set_left",
            "setRight": "set_right",
            "setBottom": "set_bottom",
            "setMargin": "set_margin",
            "setPadding": "set_padding",
            "setBorder": "set_border",
            "setBackground": "set_background",
            "setForeground": "set_foreground",
            "setOpacity": "set_opacity",
            "setVisibility": "set_visibility",
            "setDisplay": "set_display",
            "setOverflow": "set_overflow",
            "setZIndex": "set_z_index",
            "setTransform": "set_transform",
            "setTransition": "set_transition",
            "setAnimation": "set_animation",
            "setDuration": "set_duration",
            "setDelay": "set_delay",
            "setEasing": "set_easing",
            "setTiming": "set_timing",
            "setInterval": "set_interval",
            "setTimeout": "set_timeout",
            "setImmediate": "set_immediate",
            "setCallback": "set_callback",
            "setHandler": "set_handler",
            "setListener": "set_listener",
            "setEvent": "set_event",
            "setTarget": "set_target",
            "setSource": "set_source",
            "setDestination": "set_destination",
            "setOrigin": "set_origin",
            "setEndpoint": "set_endpoint",
            "setResource": "set_resource",
            "setService": "set_service",
            "setProvider": "set_provider",
            "setClient": "set_client",
            "setServer": "set_server",
            "setHost": "set_host",
            "setPort": "set_port",
            "setProtocol": "set_protocol",
            "setScheme": "set_scheme",
            "setDomain": "set_domain",
            "setSubdomain": "set_subdomain",
            "setPath": "set_path",
            "setFragment": "set_fragment",
            "setHash": "set_hash",
            "setSearch": "set_search",
            "setQueryString": "set_query_string",
            "setParameter": "set_parameter",
            "setArgument": "set_argument",
            "setOption": "set_option",
            "setSetting": "set_setting",
            "setPreference": "set_preference",
            "setDefault": "set_default",
            "setInitial": "set_initial",
            "setFinal": "set_final",
            "setCurrent": "set_current",
            "setPrevious": "set_previous",
            "setNext": "set_next",
            "setFirst": "set_first",
            "setLast": "set_last",
            "setMin": "set_min",
            "setMax": "set_max",
            "setAverage": "set_average",
            "setSum": "set_sum",
            "setProduct": "set_product",
            "setQuotient": "set_quotient",
            "setRemainder": "set_remainder",
            "setModulo": "set_modulo",
            "setPower": "set_power",
            "setRoot": "set_root",
            "setLog": "set_log",
            "setExp": "set_exp",
            "setSin": "set_sin",
            "setCos": "set_cos",
            "setTan": "set_tan",
            "setAsin": "set_asin",
            "setAcos": "set_acos",
            "setAtan": "set_atan",
            "setAtan2": "set_atan2",
            "setSinh": "set_sinh",
            "setCosh": "set_cosh",
            "setTanh": "set_tanh",
            "setAsinh": "set_asinh",
            "setAcosh": "set_acosh",
            "setAtanh": "set_atanh",
            "setCeil": "set_ceil",
            "setFloor": "set_floor",
            "setRound": "set_round",
            "setTrunc": "set_trunc",
            "setAbs": "set_abs",
            "setSign": "set_sign",
            "setRandom": "set_random",
            "setSeed": "set_seed",
            "setRange": "set_range",
            "setStep": "set_step",
            "setIncrement": "set_increment",
            "setDecrement": "set_decrement",
            "setAdd": "set_add",
            "setSubtract": "set_subtract",
            "setMultiply": "set_multiply",
            "setDivide": "set_divide",
            "setNegate": "set_negate",
            "setInvert": "set_invert",
            "setReverse": "set_reverse",
            "setFlip": "set_flip",
            "setToggle": "set_toggle",
            "setSwitch": "set_switch",
            "setChange": "set_change",
            "setUpdate": "set_update",
            "setModify": "set_modify",
            "setEdit": "set_edit",
            "setCreate": "set_create",
            "setDelete": "set_delete",
            "setRemove": "set_remove",
            "setAdd": "set_add",
            "setInsert": "set_insert",
            "setAppend": "set_append",
            "setPrepend": "set_prepend",
            "setReplace": "set_replace",
            "setSubstitute": "set_substitute",
            "setExchange": "set_exchange",
            "setSwap": "set_swap",
            "setMove": "set_move",
            "setCopy": "set_copy",
            "setClone": "set_clone",
            "setDuplicate": "set_duplicate",
            "setMirror": "set_mirror",
            "setReflect": "set_reflect",
            "setProject": "set_project",
            "setTransform": "set_transform",
            "setTranslate": "set_translate",
            "setRotate": "set_rotate",
            "setScale": "set_scale",
            "setSkew": "set_skew",
            "setMatrix": "set_matrix",
            "setVector": "set_vector",
            "setPoint": "set_point",
            "setLine": "set_line",
            "setRay": "set_ray",
            "setSegment": "set_segment",
            "setCircle": "set_circle",
            "setEllipse": "set_ellipse",
            "setRectangle": "set_rectangle",
            "setSquare": "set_square",
            "setTriangle": "set_triangle",
            "setPolygon": "set_polygon",
            "setPath": "set_path",
            "setCurve": "set_curve",
            "setBezier": "set_bezier",
            "setSpline": "set_spline",
            "setArc": "set_arc",
            "setSector": "set_sector",
            "setSegment": "set_segment",
            "setChord": "set_chord",
            "setTangent": "set_tangent",
            "setNormal": "set_normal",
            "setPerpendicular": "set_perpendicular",
            "setParallel": "set_parallel",
            "setIntersection": "set_intersection",
            "setUnion": "set_union",
            "setDifference": "set_difference",
            "setComplement": "set_complement",
            "setSubset": "set_subset",
            "setSuperset": "set_superset",
            "setElement": "set_element",
            "setMember": "set_member",
            "setBelong": "set_belong",
            "setContain": "set_contain",
            "setInclude": "set_include",
            "setExclude": "set_exclude",
            "setFilter": "set_filter",
            "setMap": "set_map",
            "setReduce": "set_reduce",
            "setFold": "set_fold",
            "setScan": "set_scan",
            "setZip": "set_zip",
            "setUnzip": "set_unzip",
            "setFlatten": "set_flatten",
            "setGroup": "set_group",
            "setPartition": "set_partition",
            "setChunk": "set_chunk",
            "setSlice": "set_slice",
            "setSplit": "set_split",
            "setJoin": "set_join",
            "setConcat": "set_concat",
            "setMerge": "set_merge",
            "setCombine": "set_combine",
            "setAggregate": "set_aggregate",
            "setAccumulate": "set_accumulate",
            "setCollect": "set_collect",
            "setGather": "set_gather",
            "setScatter": "set_scatter",
            "setDistribute": "set_distribute",
            "setSpread": "set_spread",
            "setBroadcast": "set_broadcast",
            "setMulticast": "set_multicast",
            "setUnicast": "set_unicast",
            "setAnycast": "set_anycast",
            "setGeocast": "set_geocast",
            "setMobicast": "set_mobicast",
            "setPodcast": "set_podcast",
            "setWebcast": "set_webcast",
            "setScreencast": "set_screencast",
            "setVideocast": "set_videocast",
            "setAudiocast": "set_audiocast",
            "setLivecast": "set_livecast",
            "setRecast": "set_recast",
            "setForecast": "set_forecast",
            "setNowcast": "set_nowcast",
            "setHindcast": "set_hindcast",
            "setDowncast": "set_downcast",
            "setUpcast": "set_upcast",
            "setOutcast": "set_outcast",
            "setIncast": "set_incast",
            "setOvercast": "set_overcast",
            "setUndercast": "set_undercast",
            "setSidecast": "set_sidecast",
            "setCrosscast": "set_crosscast",
            "setBackcast": "set_backcast",
            "setForwardcast": "set_forwardcast",
            "setRetrocast": "set_retrocast",
            "setProcast": "set_procast",
            "setAnticast": "set_anticast",
            "setCountercast": "set_countercast",
            "setSubcast": "set_subcast",
            "setSupercast": "set_supercast",
            "setMetacast": "set_metacast",
            "setUltracast": "set_ultracast",
            "setHypercast": "set_hypercast",
            "setMegacast": "set_megacast",
            "setGigacast": "set_gigacast",
            "setTeracast": "set_teracast",
            "setPetacast": "set_petacast",
            "setExacast": "set_exacast",
            "setZettacast": "set_zettacast",
            "setYottacast": "set_yottacast",
            
            # 数组和对象方法
            "findIndex": "find_index",
            "findLast": "find_last",
            "findLastIndex": "find_last_index",
            "forEach": "for_each",
            "indexOf": "index_of",
            "lastIndexOf": "last_index_of",
            "toString": "to_string",
            "valueOf": "value_of",
            "hasOwnProperty": "has_own_property",
            "isPrototypeOf": "is_prototype_of",
            "propertyIsEnumerable": "property_is_enumerable",
            "toLocaleString": "to_locale_string",
            "toLocaleLowerCase": "to_locale_lower_case",
            "toLocaleUpperCase": "to_locale_upper_case",
            "toLowerCase": "to_lower_case",
            "toUpperCase": "to_upper_case",
            "charAt": "char_at",
            "charCodeAt": "char_code_at",
            "codePointAt": "code_point_at",
            "fromCharCode": "from_char_code",
            "fromCodePoint": "from_code_point",
            "localeCompare": "locale_compare",
            "padStart": "pad_start",
            "padEnd": "pad_end",
            "trimStart": "trim_start",
            "trimEnd": "trim_end",
            "trimLeft": "trim_left",
            "trimRight": "trim_right",
            "startsWith": "starts_with",
            "endsWith": "ends_with",
            "includes": "includes",
            "repeat": "repeat",
            "replace": "replace",
            "replaceAll": "replace_all",
            "search": "search",
            "slice": "slice",
            "split": "split",
            "substr": "substr",
            "substring": "substring",
            "match": "match",
            "matchAll": "match_all",
            "normalize": "normalize",
            "concat": "concat",
            "join": "join",
            "pop": "pop",
            "push": "push",
            "shift": "shift",
            "unshift": "unshift",
            "reverse": "reverse",
            "sort": "sort",
            "splice": "splice",
            "copyWithin": "copy_within",
            "fill": "fill",
            "every": "every",
            "some": "some",
            "filter": "filter",
            "find": "find",
            "map": "map",
            "reduce": "reduce",
            "reduceRight": "reduce_right",
            "flatMap": "flat_map",
            "flat": "flat",
            "entries": "entries",
            "keys": "keys",
            "values": "values",
            "at": "at",
            "with": "with",
            "toReversed": "to_reversed",
            "toSorted": "to_sorted",
            "toSpliced": "to_spliced",
            "isArray": "is_array",
            "from": "from",
            "of": "of",
            "getDate": "get_date",
            "getDay": "get_day",
            "getFullYear": "get_full_year",
            "getHours": "get_hours",
            "getMilliseconds": "get_milliseconds",
            "getMinutes": "get_minutes",
            "getMonth": "get_month",
            "getSeconds": "get_seconds",
            "getTime": "get_time",
            "getTimezoneOffset": "get_timezone_offset",
            "getUTCDate": "get_utc_date",
            "getUTCDay": "get_utc_day",
            "getUTCFullYear": "get_utc_full_year",
            "getUTCHours": "get_utc_hours",
            "getUTCMilliseconds": "get_utc_milliseconds",
            "getUTCMinutes": "get_utc_minutes",
            "getUTCMonth": "get_utc_month",
            "getUTCSeconds": "get_utc_seconds",
            "getYear": "get_year",
            "setDate": "set_date",
            "setFullYear": "set_full_year",
            "setHours": "set_hours",
            "setMilliseconds": "set_milliseconds",
            "setMinutes": "set_minutes",
            "setMonth": "set_month",
            "setSeconds": "set_seconds",
            "setTime": "set_time",
            "setUTCDate": "set_utc_date",
            "setUTCFullYear": "set_utc_full_year",
            "setUTCHours": "set_utc_hours",
            "setUTCMilliseconds": "set_utc_milliseconds",
            "setUTCMinutes": "set_utc_minutes",
            "setUTCMonth": "set_utc_month",
            "setUTCSeconds": "set_utc_seconds",
            "setYear": "set_year",
            "toDateString": "to_date_string",
            "toISOString": "to_iso_string",
            "toJSON": "to_json",
            "toLocaleDateString": "to_locale_date_string",
            "toLocaleTimeString": "to_locale_time_string",
            "toTimeString": "to_time_string",
            "toUTCString": "to_utc_string",
            "parse": "parse",
            "UTC": "utc",
            "now": "now",
            "getPrototypeOf": "get_prototype_of",
            "setPrototypeOf": "set_prototype_of",
            "isExtensible": "is_extensible",
            "preventExtensions": "prevent_extensions",
            "getOwnPropertyDescriptor": "get_own_property_descriptor",
            "getOwnPropertyDescriptors": "get_own_property_descriptors",
            "getOwnPropertyNames": "get_own_property_names",
            "getOwnPropertySymbols": "get_own_property_symbols",
            "defineProperty": "define_property",
            "defineProperties": "define_properties",
            "seal": "seal",
            "freeze": "freeze",
            "isSealed": "is_sealed",
            "isFrozen": "is_frozen",
            "assign": "assign",
            "create": "create",
            "is": "is",
            "fromEntries": "from_entries",
            "hasOwn": "has_own",
            "groupBy": "group_by",
            "isNaN": "is_nan",
            "isFinite": "is_finite",
            "parseInt": "parse_int",
            "parseFloat": "parse_float",
            "encodeURI": "encode_uri",
            "encodeURIComponent": "encode_uri_component",
            "decodeURI": "decode_uri",
            "decodeURIComponent": "decode_uri_component",
            "escape": "escape",
            "unescape": "unescape",
            "eval": "eval",
            "isInteger": "is_integer",
            "isSafeInteger": "is_safe_integer",
            "toExponential": "to_exponential",
            "toFixed": "to_fixed",
            "toPrecision": "to_precision",
            "toSource": "to_source",
            "compile": "compile",
            "exec": "exec",
            "test": "test",
            "global": "global",
            "ignoreCase": "ignore_case",
            "lastIndex": "last_index",
            "multiline": "multiline",
            "source": "source",
            "sticky": "sticky",
            "unicode": "unicode",
            "dotAll": "dot_all",
            "flags": "flags",
            "hasIndices": "has_indices",
            "apply": "apply",
            "call": "call",
            "bind": "bind",
            "toString": "to_string",
            "valueOf": "value_of",
            "constructor": "constructor",
            "length": "length",
            "name": "name",
            "prototype": "prototype",
            "arguments": "arguments",
            "caller": "caller",
            "displayName": "display_name",
            "arity": "arity",
            "getItem": "get_item",
            "setItem": "set_item",
            "removeItem": "remove_item",
            "clear": "clear",
            "key": "key",
            "getOwnPropertyNames": "get_own_property_names",
            "addEventListener": "add_event_listener",
            "removeEventListener": "remove_event_listener",
            "dispatchEvent": "dispatch_event",
            "preventDefault": "prevent_default",
            "stopPropagation": "stop_propagation",
            "stopImmediatePropagation": "stop_immediate_propagation",
            "initEvent": "init_event",
            "createEvent": "create_event",
            "getElementById": "get_element_by_id",
            "getElementsByTagName": "get_elements_by_tag_name",
            "getElementsByClassName": "get_elements_by_class_name",
            "getElementsByName": "get_elements_by_name",
            "querySelector": "query_selector",
            "querySelectorAll": "query_selector_all",
            "createElement": "create_element",
            "createTextNode": "create_text_node",
            "createComment": "create_comment",
            "createDocumentFragment": "create_document_fragment",
            "createAttribute": "create_attribute",
            "createAttributeNS": "create_attribute_ns",
            "createElementNS": "create_element_ns",
            "importNode": "import_node",
            "adoptNode": "adopt_node",
            "normalize": "normalize",
            "renameNode": "rename_node",
            "appendChild": "append_child",
            "insertBefore": "insert_before",
            "replaceChild": "replace_child",
            "removeChild": "remove_child",
            "cloneNode": "clone_node",
            "compareDocumentPosition": "compare_document_position",
            "contains": "contains",
            "lookupPrefix": "lookup_prefix",
            "lookupNamespaceURI": "lookup_namespace_uri",
            "isDefaultNamespace": "is_default_namespace",
            "insertAdjacentElement": "insert_adjacent_element",
            "insertAdjacentHTML": "insert_adjacent_html",
            "insertAdjacentText": "insert_adjacent_text",
            "getAttribute": "get_attribute",
            "getAttributeNS": "get_attribute_ns",
            "getAttributeNode": "get_attribute_node",
            "getAttributeNodeNS": "get_attribute_node_ns",
            "setAttribute": "set_attribute",
            "setAttributeNS": "set_attribute_ns",
            "setAttributeNode": "set_attribute_node",
            "setAttributeNodeNS": "set_attribute_node_ns",
            "removeAttribute": "remove_attribute",
            "removeAttributeNS": "remove_attribute_ns",
            "removeAttributeNode": "remove_attribute_node",
            "hasAttribute": "has_attribute",
            "hasAttributeNS": "has_attribute_ns",
            "hasAttributes": "has_attributes",
            "getClientRects": "get_client_rects",
            "getBoundingClientRect": "get_bounding_client_rect",
            "scrollIntoView": "scroll_into_view",
            "scrollIntoViewIfNeeded": "scroll_into_view_if_needed",
            "scrollByLines": "scroll_by_lines",
            "scrollByPages": "scroll_by_pages",
            "getElementsByTagName": "get_elements_by_tag_name",
            "getElementsByTagNameNS": "get_elements_by_tag_name_ns",
            "getElementsByClassName": "get_elements_by_class_name",
            "querySelector": "query_selector",
            "querySelectorAll": "query_selector_all",
            "matches": "matches",
            "webkitMatchesSelector": "webkit_matches_selector",
            "mozMatchesSelector": "moz_matches_selector",
            "msMatchesSelector": "ms_matches_selector",
            "oMatchesSelector": "o_matches_selector",
            "closest": "closest",
            "animate": "animate",
            "getAnimations": "get_animations",
            "before": "before",
            "after": "after",
            "replaceWith": "replace_with",
            "remove": "remove",
            "prepend": "prepend",
            "append": "append",
            "requestFullscreen": "request_fullscreen",
            "webkitRequestFullscreen": "webkit_request_fullscreen",
            "mozRequestFullScreen": "moz_request_full_screen",
            "msRequestFullscreen": "ms_request_fullscreen",
            "exitFullscreen": "exit_fullscreen",
            "webkitExitFullscreen": "webkit_exit_fullscreen",
            "mozCancelFullScreen": "moz_cancel_full_screen",
            "msExitFullscreen": "ms_exit_fullscreen",
            "requestPointerLock": "request_pointer_lock",
            "webkitRequestPointerLock": "webkit_request_pointer_lock",
            "mozRequestPointerLock": "moz_request_pointer_lock",
            "exitPointerLock": "exit_pointer_lock",
            "webkitExitPointerLock": "webkit_exit_pointer_lock",
            "mozExitPointerLock": "moz_exit_pointer_lock",
            "setPointerCapture": "set_pointer_capture",
            "releasePointerCapture": "release_pointer_capture",
            "hasPointerCapture": "has_pointer_capture",
            "setCapture": "set_capture",
            "releaseCapture": "release_capture",
            "focus": "focus",
            "blur": "blur",
            "click": "click",
            "submit": "submit",
            "reset": "reset",
            "select": "select",
            "setSelectionRange": "set_selection_range",
            "setRangeText": "set_range_text",
            "checkValidity": "check_validity",
            "reportValidity": "report_validity",
            "setCustomValidity": "set_custom_validity",
            "stepUp": "step_up",
            "stepDown": "step_down",
            "showModal": "show_modal",
            "show": "show",
            "close": "close",
            "open": "open",
            "toggle": "toggle",
            "add": "add",
            "remove": "remove",
            "item": "item",
            "namedItem": "named_item",
            "getNamedItem": "get_named_item",
            "setNamedItem": "set_named_item",
            "removeNamedItem": "remove_named_item",
            "getNamedItemNS": "get_named_item_ns",
            "setNamedItemNS": "set_named_item_ns",
            "removeNamedItemNS": "remove_named_item_ns",
            "item": "item",
            "namedItem": "named_item",
            "add": "add",
            "remove": "remove",
            "toggle": "toggle",
            "contains": "contains",
            "replace": "replace",
            "supports": "supports",
            "forEach": "for_each",
            "entries": "entries",
            "keys": "keys",
            "values": "values",
            "getPropertyValue": "get_property_value",
            "getPropertyPriority": "get_property_priority",
            "setProperty": "set_property",
            "removeProperty": "remove_property",
            "item": "item",
            "getComputedStyle": "get_computed_style",
            "matchMedia": "match_media",
            "getSelection": "get_selection",
            "createRange": "create_range",
            "caretRangeFromPoint": "caret_range_from_point",
            "caretPositionFromPoint": "caret_position_from_point",
            "elementFromPoint": "element_from_point",
            "elementsFromPoint": "elements_from_point",
            "scrollingElement": "scrolling_element",
            "activeElement": "active_element",
            "hasFocus": "has_focus",
            "designMode": "design_mode",
            "execCommand": "exec_command",
            "queryCommandEnabled": "query_command_enabled",
            "queryCommandIndeterm": "query_command_indeterm",
            "queryCommandState": "query_command_state",
            "queryCommandSupported": "query_command_supported",
            "queryCommandValue": "query_command_value",
            "write": "write",
            "writeln": "writeln",
            "open": "open",
            "close": "close",
            "clear": "clear",
            "captureEvents": "capture_events",
            "releaseEvents": "release_events",
            "routeEvent": "route_event",
            "enableStyleSheetsForSet": "enable_style_sheets_for_set",
            "caretRangeFromPoint": "caret_range_from_point",
            "createNodeIterator": "create_node_iterator",
            "createTreeWalker": "create_tree_walker",
            "createExpression": "create_expression",
            "createNSResolver": "create_ns_resolver",
            "evaluate": "evaluate",
            "exitPictureInPicture": "exit_picture_in_picture",
            "getElementById": "get_element_by_id",
            "getElementsByName": "get_elements_by_name",
            "getElementsByTagName": "get_elements_by_tag_name",
            "getElementsByTagNameNS": "get_elements_by_tag_name_ns",
            "getElementsByClassName": "get_elements_by_class_name",
            "querySelector": "query_selector",
            "querySelectorAll": "query_selector_all",
            "createAttribute": "create_attribute",
            "createAttributeNS": "create_attribute_ns",
            "createCDATASection": "create_cdata_section",
            "createComment": "create_comment",
            "createDocumentFragment": "create_document_fragment",
            "createElement": "create_element",
            "createElementNS": "create_element_ns",
            "createEntityReference": "create_entity_reference",
            "createEvent": "create_event",
            "createProcessingInstruction": "create_processing_instruction",
            "createRange": "create_range",
            "createTextNode": "create_text_node",
            "createTouch": "create_touch",
            "createTouchList": "create_touch_list",
            "elementFromPoint": "element_from_point",
            "elementsFromPoint": "elements_from_point",
            "enableStyleSheetsForSet": "enable_style_sheets_for_set",
            "exitFullscreen": "exit_fullscreen",
            "exitPictureInPicture": "exit_picture_in_picture",
            "exitPointerLock": "exit_pointer_lock",
            "getAnimations": "get_animations",
            "getSelection": "get_selection",
            "hasFocus": "has_focus",
            "importNode": "import_node",
            "prepend": "prepend",
            "append": "append",
            "replaceChildren": "replace_children",
            "requestStorageAccess": "request_storage_access",
            "hasStorageAccess": "has_storage_access",
            "startViewTransition": "start_view_transition",
            "webkitCancelFullScreen": "webkit_cancel_full_screen",
            "webkitCurrentFullScreenElement": "webkit_current_full_screen_element",
            "webkitExitFullscreen": "webkit_exit_fullscreen",
            "webkitFullscreenElement": "webkit_fullscreen_element",
            "webkitFullscreenEnabled": "webkit_fullscreen_enabled",
            "webkitIsFullScreen": "webkit_is_full_screen",
            "mozCancelFullScreen": "moz_cancel_full_screen",
            "mozFullScreen": "moz_full_screen",
            "mozFullScreenElement": "moz_full_screen_element",
            "mozFullScreenEnabled": "moz_full_screen_enabled",
            "msExitFullscreen": "ms_exit_fullscreen",
            "msFullscreenElement": "ms_fullscreen_element",
            "msFullscreenEnabled": "ms_fullscreen_enabled",
            "onabort": "on_abort",
            "onanimationcancel": "on_animation_cancel",
            "onanimationend": "on_animation_end",
            "onanimationiteration": "on_animation_iteration",
            "onanimationstart": "on_animation_start",
            "onauxclick": "on_aux_click",
            "onbeforeinput": "on_before_input",
            "onblur": "on_blur",
            "oncancel": "on_cancel",
            "oncanplay": "on_can_play",
            "oncanplaythrough": "on_can_play_through",
            "onchange": "on_change",
            "onclick": "on_click",
            "onclose": "on_close",
            "oncontextmenu": "on_context_menu",
            "oncopy": "on_copy",
            "oncuechange": "on_cue_change",
            "oncut": "on_cut",
            "ondblclick": "on_dbl_click",
            "ondrag": "on_drag",
            "ondragend": "on_drag_end",
            "ondragenter": "on_drag_enter",
            "ondragleave": "on_drag_leave",
            "ondragover": "on_drag_over",
            "ondragstart": "on_drag_start",
            "ondrop": "on_drop",
            "ondurationchange": "on_duration_change",
            "onemptied": "on_emptied",
            "onended": "on_ended",
            "onerror": "on_error",
            "onfocus": "on_focus",
            "onformdata": "on_form_data",
            "onfullscreenchange": "on_fullscreen_change",
            "onfullscreenerror": "on_fullscreen_error",
            "ongotpointercapture": "on_got_pointer_capture",
            "oninput": "on_input",
            "oninvalid": "on_invalid",
            "onkeydown": "on_key_down",
            "onkeypress": "on_key_press",
            "onkeyup": "on_key_up",
            "onload": "on_load",
            "onloadeddata": "on_loaded_data",
            "onloadedmetadata": "on_loaded_metadata",
            "onloadstart": "on_load_start",
            "onlostpointercapture": "on_lost_pointer_capture",
            "onmousedown": "on_mouse_down",
            "onmouseenter": "on_mouse_enter",
            "onmouseleave": "on_mouse_leave",
            "onmousemove": "on_mouse_move",
            "onmouseout": "on_mouse_out",
            "onmouseover": "on_mouse_over",
            "onmouseup": "on_mouse_up",
            "onpaste": "on_paste",
            "onpause": "on_pause",
            "onplay": "on_play",
            "onplaying": "on_playing",
            "onpointercancel": "on_pointer_cancel",
            "onpointerdown": "on_pointer_down",
            "onpointerenter": "on_pointer_enter",
            "onpointerleave": "on_pointer_leave",
            "onpointerlockchange": "on_pointer_lock_change",
            "onpointerlockerror": "on_pointer_lock_error",
            "onpointermove": "on_pointer_move",
            "onpointerout": "on_pointer_out",
            "onpointerover": "on_pointer_over",
            "onpointerup": "on_pointer_up",
            "onprogress": "on_progress",
            "onratechange": "on_rate_change",
            "onreset": "on_reset",
            "onresize": "on_resize",
            "onscroll": "on_scroll",
            "onsecuritypolicyviolation": "on_security_policy_violation",
            "onseeked": "on_seeked",
            "onseeking": "on_seeking",
            "onselect": "on_select",
            "onselectionchange": "on_selection_change",
            "onselectstart": "on_select_start",
            "onslotchange": "on_slot_change",
            "onstalled": "on_stalled",
            "onsubmit": "on_submit",
            "onsuspend": "on_suspend",
            "ontimeupdate": "on_time_update",
            "ontoggle": "on_toggle",
            "ontouchcancel": "on_touch_cancel",
            "ontouchend": "on_touch_end",
            "ontouchmove": "on_touch_move",
            "ontouchstart": "on_touch_start",
            "ontransitioncancel": "on_transition_cancel",
            "ontransitionend": "on_transition_end",
            "ontransitionrun": "on_transition_run",
            "ontransitionstart": "on_transition_start",
            "onvolumechange": "on_volume_change",
            "onwaiting": "on_waiting",
            "onwebkitanimationend": "on_webkit_animation_end",
            "onwebkitanimationiteration": "on_webkit_animation_iteration",
            "onwebkitanimationstart": "on_webkit_animation_start",
            "onwebkittransitionend": "on_webkit_transition_end",
            "onwheel": "on_wheel",
            
            # 对象属性
            "isActive": "is_active",
            "isDeleted": "is_deleted",
            "isLoading": "is_loading",
            "isVisible": "is_visible",
            "isDisabled": "is_disabled",
            "isSelected": "is_selected",
            "isOpen": "is_open",
            "isClosed": "is_closed",
            "isValid": "is_valid",
            "isInvalid": "is_invalid",
            "isRequired": "is_required",
            "isOptional": "is_optional",
            "isReadonly": "is_readonly",
            "isEditable": "is_editable",
            "isChecked": "is_checked",
            "isUnchecked": "is_unchecked",
            "isExpanded": "is_expanded",
            "isCollapsed": "is_collapsed",
            "isHidden": "is_hidden",
            "isShown": "is_shown",
            "isEnabled": "is_enabled",
            "isFocused": "is_focused",
            "isBlurred": "is_blurred",
            "isHovered": "is_hovered",
            "isPressed": "is_pressed",
            "isReleased": "is_released",
            "isDragging": "is_dragging",
            "isDropping": "is_dropping",
            "isResizing": "is_resizing",
            "isMoving": "is_moving",
            "isRotating": "is_rotating",
            "isScaling": "is_scaling",
            "isAnimating": "is_animating",
            "isTransitioning": "is_transitioning",
            "isPlaying": "is_playing",
            "isPaused": "is_paused",
            "isStopped": "is_stopped",
            "isRecording": "is_recording",
            "isStreaming": "is_streaming",
            "isBuffering": "is_buffering",
            "isConnected": "is_connected",
            "isDisconnected": "is_disconnected",
            "isOnline": "is_online",
            "isOffline": "is_offline",
            "isLoggedIn": "is_logged_in",
            "isLoggedOut": "is_logged_out",
            "isAuthenticated": "is_authenticated",
            "isUnauthenticated": "is_unauthenticated",
            "isAuthorized": "is_authorized",
            "isUnauthorized": "is_unauthorized",
            "isAdmin": "is_admin",
            "isUser": "is_user",
            "isGuest": "is_guest",
            "isMember": "is_member",
            "isOwner": "is_owner",
            "isModerator": "is_moderator",
            "isEditor": "is_editor",
            "isViewer": "is_viewer",
            "isContributor": "is_contributor",
            "isSubscriber": "is_subscriber",
            "isFollower": "is_follower",
            "isFriend": "is_friend",
            "isBlocked": "is_blocked",
            "isMuted": "is_muted",
            "isBanned": "is_banned",
            "isSuspended": "is_suspended",
            "isVerified": "is_verified",
            "isUnverified": "is_unverified",
            "isPending": "is_pending",
            "isApproved": "is_approved",
            "isRejected": "is_rejected",
            "isCancelled": "is_cancelled",
            "isCompleted": "is_completed",
            "isIncomplete": "is_incomplete",
            "isSuccessful": "is_successful",
            "isFailed": "is_failed",
            "isError": "is_error",
            "isWarning": "is_warning",
            "isInfo": "is_info",
            "isDebug": "is_debug",
            "isTrace": "is_trace",
            "isFatal": "is_fatal",
            "isCritical": "is_critical",
            "isHigh": "is_high",
            "isMedium": "is_medium",
            "isLow": "is_low",
            "isUrgent": "is_urgent",
            "isNormal": "is_normal",
            "isImportant": "is_important",
            "isUnimportant": "is_unimportant",
            "isPublic": "is_public",
            "isPrivate": "is_private",
            "isProtected": "is_protected",
            "isInternal": "is_internal",
            "isExternal": "is_external",
            "isLocal": "is_local",
            "isRemote": "is_remote",
            "isGlobal": "is_global",
            "isStatic": "is_static",
            "isDynamic": "is_dynamic",
            "isAbstract": "is_abstract",
            "isConcrete": "is_concrete",
            "isVirtual": "is_virtual",
            "isReal": "is_real",
            "isFake": "is_fake",
            "isMock": "is_mock",
            "isStub": "is_stub",
            "isSpy": "is_spy",
            "isProxy": "is_proxy",
            "isWrapper": "is_wrapper",
            "isAdapter": "is_adapter",
            "isBridge": "is_bridge",
            "isComposite": "is_composite",
            "isDecorator": "is_decorator",
            "isFacade": "is_facade",
            "isFlyweight": "is_flyweight",
            "isProxy": "is_proxy",
            "isChain": "is_chain",
            "isCommand": "is_command",
            "isInterpreter": "is_interpreter",
            "isIterator": "is_iterator",
            "isMediator": "is_mediator",
            "isMemento": "is_memento",
            "isObserver": "is_observer",
            "isState": "is_state",
            "isStrategy": "is_strategy",
            "isTemplate": "is_template",
            "isVisitor": "is_visitor",
            "isAbstractFactory": "is_abstract_factory",
            "isBuilder": "is_builder",
            "isFactoryMethod": "is_factory_method",
            "isPrototype": "is_prototype",
            "isSingleton": "is_singleton",
            "lastLoginAt": "last_login_at",
            "createdAt": "created_at",
            "updatedAt": "updated_at",
            "deletedAt": "deleted_at",
            "publishedAt": "published_at",
            "archivedAt": "archived_at",
            "expiredAt": "expired_at",
            "startedAt": "started_at",
            "finishedAt": "finished_at",
            "completedAt": "completed_at",
            "cancelledAt": "cancelled_at",
            "suspendedAt": "suspended_at",
            "resumedAt": "resumed_at",
            "pausedAt": "paused_at",
            "stoppedAt": "stopped_at",
            "restartedAt": "restarted_at",
            "resetAt": "reset_at",
            "clearedAt": "cleared_at",
            "savedAt": "saved_at",
            "loadedAt": "loaded_at",
            "importedAt": "imported_at",
            "exportedAt": "exported_at",
            "uploadedAt": "uploaded_at",
            "downloadedAt": "downloaded_at",
            "sentAt": "sent_at",
            "receivedAt": "received_at",
            "deliveredAt": "delivered_at",
            "readAt": "read_at",
            "viewedAt": "viewed_at",
            "clickedAt": "clicked_at"
        }
        
        # 变量声明模式
        self.variable_patterns = [
            # const [camelCase] = useState()
            (r'const\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=\s*useState', r'const \1 = use_state'),
            # const [camelCase] = useEffect()
            (r'const\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=\s*useEffect', r'const \1 = use_effect'),
            # let camelCase = value
            (r'let\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=', r'let \1 ='),
            # var camelCase = value
            (r'var\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=', r'var \1 =')
        ]
        
    def create_backup(self):
        """创建备份目录"""
        if self.backup_dir.exists():
            shutil.rmtree(self.backup_dir)
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        print(f"✅ 备份目录已创建: {self.backup_dir}")
    
    def backup_file(self, file_path: Path):
        """备份单个文件"""
        relative_path = file_path.relative_to(self.src_dir)
        backup_path = self.backup_dir / relative_path
        backup_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(file_path, backup_path)
    
    def camel_to_snake(self, name: str) -> str:
        """将驼峰命名转换为蛇形命名"""
        # 处理连续大写字母
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    
    def process_file(self, file_path: Path) -> bool:
        """处理单个文件"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            original_content = content
            file_modifications = []
            
            # 1. 处理React Hooks和函数调用
            for camel, snake in self.camel_to_snake_mappings.items():
                # 函数调用模式: functionName(
                pattern = rf'\b{re.escape(camel)}\s*\('
                replacement = f'{snake}('
                
                matches = list(re.finditer(pattern, content))
                if matches:
                    content = re.sub(pattern, replacement, content)
                    file_modifications.append({
                        'type': 'function_call',
                        'original': camel,
                        'replacement': snake,
                        'count': len(matches)
                    })
                    self.stats['replacement_types']['function_calls'] += len(matches)
            
            # 2. 处理对象属性
            for camel, snake in self.camel_to_snake_mappings.items():
                # 对象属性模式: .propertyName
                pattern = rf'\.{re.escape(camel)}\b'
                replacement = f'.{snake}'
                
                matches = list(re.finditer(pattern, content))
                if matches:
                    content = re.sub(pattern, replacement, content)
                    file_modifications.append({
                        'type': 'object_property',
                        'original': camel,
                        'replacement': snake,
                        'count': len(matches)
                    })
                    self.stats['replacement_types']['object_properties'] += len(matches)
            
            # 3. 处理变量声明中的驼峰命名
            camel_var_pattern = r'\b([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\b'
            
            def replace_camel_vars(match):
                camel_name = match.group(1)
                snake_name = self.camel_to_snake(camel_name)
                return snake_name
            
            # 在变量声明中查找驼峰变量
            var_decl_patterns = [
                r'const\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=',
                r'let\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*=',
                r'var\s+([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*)\s*='
            ]
            
            for pattern in var_decl_patterns:
                matches = list(re.finditer(pattern, content))
                for match in matches:
                    camel_name = match.group(1)
                    snake_name = self.camel_to_snake(camel_name)
                    
                    # 替换声明
                    old_decl = match.group(0)
                    new_decl = old_decl.replace(camel_name, snake_name)
                    content = content.replace(old_decl, new_decl)
                    
                    # 替换该变量的所有使用
                    var_usage_pattern = rf'\b{re.escape(camel_name)}\b'
                    usage_matches = list(re.finditer(var_usage_pattern, content))
                    content = re.sub(var_usage_pattern, snake_name, content)
                    
                    file_modifications.append({
                        'type': 'variable_declaration',
                        'original': camel_name,
                        'replacement': snake_name,
                        'count': len(usage_matches) + 1  # +1 for declaration
                    })
                    self.stats['replacement_types']['variable_declarations'] += len(usage_matches) + 1
            
            # 4. 处理React Hooks特殊情况
            react_hooks = ['useState', 'useEffect', 'useContext', 'useReducer', 'useCallback', 'useMemo', 'useRef']
            for hook in react_hooks:
                snake_hook = self.camel_to_snake(hook)
                pattern = rf'\b{re.escape(hook)}\b'
                matches = list(re.finditer(pattern, content))
                if matches:
                    content = re.sub(pattern, snake_hook, content)
                    file_modifications.append({
                        'type': 'react_hook',
                        'original': hook,
                        'replacement': snake_hook,
                        'count': len(matches)
                    })
                    self.stats['replacement_types']['react_hooks'] += len(matches)
            
            # 5. 处理数组和字符串方法
            array_methods = ['findIndex', 'forEach', 'indexOf', 'lastIndexOf', 'toString', 'valueOf']
            for method in array_methods:
                snake_method = self.camel_to_snake(method)
                pattern = rf'\.{re.escape(method)}\s*\('
                replacement = f'.{snake_method}('
                matches = list(re.finditer(pattern, content))
                if matches:
                    content = re.sub(pattern, replacement, content)
                    file_modifications.append({
                        'type': 'method_call',
                        'original': method,
                        'replacement': snake_method,
                        'count': len(matches)
                    })
                    self.stats['replacement_types']['method_calls'] += len(matches)
            
            # 检查是否有修改
            if content != original_content:
                # 备份原文件
                self.backup_file(file_path)
                
                # 写入修改后的内容
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                # 记录修改
                total_changes = sum(mod['count'] for mod in file_modifications)
                self.modifications.append({
                    'file': str(file_path),
                    'changes': file_modifications,
                    'total_changes': total_changes
                })
                
                self.stats['files_modified'] += 1
                self.stats['total_replacements'] += total_changes
                
                print(f"✅ 已修改: {file_path.name} ({total_changes} 处修改)")
                return True
            else:
                print(f"⏭️  跳过: {file_path.name} (无需修改)")
                return False
                
        except Exception as e:
            print(f"❌ 处理文件失败 {file_path}: {e}")
            return False
    
    def process_all_files(self):
        """处理所有TypeScript文件"""
        print("🚀 开始第二阶段：变量命名统一...")
        
        # 创建备份
        self.create_backup()
        
        # 查找所有TypeScript文件
        ts_files = list(self.src_dir.rglob("*.ts")) + list(self.src_dir.rglob("*.tsx"))
        
        print(f"📁 找到 {len(ts_files)} 个TypeScript文件")
        
        for file_path in ts_files:
            self.stats['files_processed'] += 1
            self.process_file(file_path)
        
        # 生成报告
        self.generate_report()
        
        print("\n🎉 第二阶段变量命名统一完成！")
        print(f"📊 处理文件: {self.stats['files_processed']} 个")
        print(f"📝 修改文件: {self.stats['files_modified']} 个")
        print(f"🔄 总替换数: {self.stats['total_replacements']} 处")
        print(f"📋 详细报告: {self.report_file}")
    
    def generate_report(self):
        """生成详细报告"""
        report = {
            'timestamp': self.timestamp,
            'stage': 'Stage 2: Variable Naming Unification',
            'summary': self.stats,
            'modifications': self.modifications,
            'mappings_used': self.camel_to_snake_mappings
        }
        
        with open(self.report_file, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        
        print(f"📄 报告已生成: {self.report_file}")

def main():
    """主函数"""
    unifier = Stage2NamingUnifier()
    unifier.process_all_files()

if __name__ == "__main__":
    main()